DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  SAMPLER: softmax_triplet
DATASETS:
  NAMES:
  - UAM
  ROOT_DIR: /home/mdb/DL_Lab3/ST_DATASETS/ALL_COMBINED_RIVAS/Unified/
INPUT:
  PADDING: 10
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST:
  - 256
  - 256
  SIZE_TRAIN:
  - 256
  - 256
MODEL:
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  METRIC_LOSS_TYPE: triplet_center
  NAME: se_resnet50
  PRETRAIN_CHOICE: imagenet
  PRETRAIN_PATH: /home/mdb/reid-strong-baseline/configs/se_resnet50-ce0d4300.pth
OUTPUT_DIR: /home/mdb/reid-strong-baseline/TRANSFER_Learning_SR_ensembling_BestEnsemb_85ep/Unified_se_resnet50_base/RIVAS
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 10
  CLUSTER_MARGIN: 0.3
  EVAL_PERIOD: 1005
  GAMMA: 0.1
  IMS_PER_BATCH: 64
  LOG_PERIOD: 5
  MAX_EPOCHS: 85
  OPTIMIZER_NAME: Adam
  RANGE_ALPHA: 0
  RANGE_BETA: 1.0
  RANGE_K: 2
  RANGE_LOSS_WEIGHT: 1
  RANGE_MARGIN: 0.3
  STEPS:
  - 40
  - 70
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  IMS_PER_BATCH: 128
  NECK_FEAT: after
  RE_RANKING: 'no'
